apiVersion: apps/v1
kind: Deployment
metadata:
  name: uhuy-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: uhuy-ui
          image: yansetiaji/uhuy-ui:v0
          ports:
            - containerPort: 3000
          env:
            - name: NUXT_PUBLIC_BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: uhuy-ui-configmap 
                  key: NUXT_PUBLIC_BACKEND_HOST

