apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uhuy-ui-ingress
spec:
  rules:
    - host: uhuy-ui.cicicuit.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uhuy-ui-service
                port:
                  number: 3000
